CREATE TABLE IF NOT EXISTS facilities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'sq ft'
);

CREATE TABLE IF NOT EXISTS zones (
  id TEXT PRIMARY KEY,
  facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zone_type TEXT NOT NULL CHECK (zone_type IN ('warehouse', 'workstation', 'dock', 'support')),
  process_order INTEGER,
  area_sq_ft INTEGER NOT NULL,
  primary_flow TEXT NOT NULL,
  status TEXT NOT NULL,
  description TEXT NOT NULL,
  -- Units the station can work on at once; NULL = unconstrained. Orders larger
  -- than capacity run in batches, multiplying the station's cycle time.
  capacity INTEGER,
  map_x INTEGER NOT NULL,
  map_y INTEGER NOT NULL,
  map_width INTEGER NOT NULL,
  map_height INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  material_type TEXT NOT NULL CHECK (material_type IN ('raw', 'wip', 'finished')),
  default_zone_id TEXT NOT NULL REFERENCES zones(id)
);

CREATE TABLE IF NOT EXISTS process_steps (
  id TEXT PRIMARY KEY,
  facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  step_number INTEGER NOT NULL,
  source_zone_id TEXT NOT NULL REFERENCES zones(id),
  target_zone_id TEXT NOT NULL REFERENCES zones(id),
  name TEXT NOT NULL,
  expected_minutes INTEGER NOT NULL,
  -- Costing baseline: the standard cycle. Editing a station's cycle changes
  -- expected_minutes only, so the ratio drives labor efficiency variance.
  standard_minutes INTEGER,
  route_type TEXT NOT NULL CHECK (route_type IN ('material', 'return', 'rework'))
);

CREATE TABLE IF NOT EXISTS inventory_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id INTEGER NOT NULL REFERENCES materials(id),
  zone_id TEXT NOT NULL REFERENCES zones(id),
  quantity_on_hand INTEGER NOT NULL DEFAULT 0,
  reorder_point INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (material_id, zone_id)
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT NOT NULL CONSTRAINT inventory_items_area_check CHECK (area IN ('Parts', 'Production', 'Sub-assembly', 'Finished Goods')),
  location_zone_id TEXT NOT NULL REFERENCES zones(id),
  item_name TEXT NOT NULL,
  part_number TEXT NOT NULL,
  quantity_on_hand NUMERIC(12, 3) NOT NULL DEFAULT 0,
  quantity_allocated NUMERIC(12, 3) NOT NULL DEFAULT 0,
  quantity_available NUMERIC(12, 3) GENERATED ALWAYS AS (quantity_on_hand - quantity_allocated) STORED,
  unit TEXT NOT NULL,
  min_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  max_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('Ready', 'Watch', 'Reorder', 'In process', 'Open capacity', 'Clear')),
  control_note TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (area, location_zone_id, part_number)
);

CREATE TABLE IF NOT EXISTS work_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_order_no TEXT NOT NULL UNIQUE,
  material_id INTEGER NOT NULL REFERENCES materials(id),
  current_zone_id TEXT NOT NULL REFERENCES zones(id),
  quantity INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('planned', 'in_progress', 'hold', 'complete')),
  due_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS production_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL UNIQUE,
  finished_material_id INTEGER NOT NULL REFERENCES materials(id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  status TEXT NOT NULL CHECK (status IN ('planned', 'released', 'in_progress', 'hold', 'complete', 'cancelled')),
  current_zone_id TEXT NOT NULL REFERENCES zones(id),
  start_date DATE NOT NULL,
  due_date DATE NOT NULL,
  -- Queue sequence: lower runs first, created_at breaks ties. Re-sequencing
  -- assigns 10, 20, 30... so new orders (default 1000) join the back of the line.
  priority INTEGER NOT NULL DEFAULT 1000,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bom_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_material_id INTEGER NOT NULL REFERENCES materials(id),
  part_number TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  quantity NUMERIC(12, 3) NOT NULL,
  unit TEXT NOT NULL,
  station_zone_id TEXT REFERENCES zones(id),
  source_zone_id TEXT REFERENCES zones(id),
  supply_type TEXT NOT NULL CHECK (supply_type IN ('make', 'buy')),
  -- Material-release attributes: serialized parts must be captured on the
  -- build record; a substitute keeps the kit releasable when the primary is short.
  serialized BOOLEAN NOT NULL DEFAULT FALSE,
  substitute_part_number TEXT,
  notes TEXT NOT NULL,
  CONSTRAINT bom_items_parent_part_unique UNIQUE (parent_material_id, part_number)
);

CREATE TABLE IF NOT EXISTS production_order_materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  bom_item_id INTEGER REFERENCES bom_items(id),
  part_number TEXT NOT NULL,
  description TEXT NOT NULL,
  required_quantity NUMERIC(12, 3) NOT NULL,
  issued_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  consumed_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  unit TEXT NOT NULL,
  source_zone_id TEXT NOT NULL REFERENCES zones(id),
  status TEXT NOT NULL CHECK (status IN ('planned', 'allocated', 'issued', 'consumed', 'short')),
  UNIQUE (production_order_id, part_number)
);

CREATE TABLE IF NOT EXISTS production_order_operations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  process_step_id TEXT REFERENCES process_steps(id),
  sequence_number INTEGER NOT NULL,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  operation_name TEXT NOT NULL,
  planned_minutes INTEGER NOT NULL,
  actual_minutes INTEGER NOT NULL DEFAULT 0,
  quantity_in INTEGER NOT NULL DEFAULT 0,
  quantity_out INTEGER NOT NULL DEFAULT 0,
  scrap_quantity INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('queued', 'ready', 'in_progress', 'complete', 'hold')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  UNIQUE (production_order_id, sequence_number)
);

CREATE TABLE IF NOT EXISTS workstation_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  wip_quantity INTEGER NOT NULL DEFAULT 0,
  completed_quantity INTEGER NOT NULL DEFAULT 0,
  hold_quantity INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (production_order_id, zone_id)
);

CREATE TABLE IF NOT EXISTS production_order_activity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  operation_id INTEGER REFERENCES production_order_operations(id) ON DELETE SET NULL,
  activity_type TEXT NOT NULL CHECK (activity_type IN ('created', 'released', 'material_issued', 'started', 'moved', 'completed', 'held', 'reworked', 'adjusted')),
  from_zone_id TEXT REFERENCES zones(id),
  to_zone_id TEXT REFERENCES zones(id),
  quantity INTEGER NOT NULL DEFAULT 0,
  notes TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER REFERENCES production_orders(id) ON DELETE SET NULL,
  inventory_item_id INTEGER REFERENCES inventory_items(id) ON DELETE SET NULL,
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('create', 'allocate', 'issue', 'consume', 'move', 'complete', 'adjust', 'rework')),
  from_zone_id TEXT REFERENCES zones(id),
  to_zone_id TEXT REFERENCES zones(id),
  part_number TEXT NOT NULL,
  quantity NUMERIC(12, 3) NOT NULL,
  unit TEXT NOT NULL,
  reference TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS production_workstation_ledger (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('in', 'out', 'adjustment', 'hold', 'scrap')),
  quantity_in NUMERIC(12, 3) NOT NULL DEFAULT 0,
  quantity_out NUMERIC(12, 3) NOT NULL DEFAULT 0,
  adjustment_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  balance_after NUMERIC(12, 3) NOT NULL DEFAULT 0,
  accounting_event TEXT NOT NULL,
  reference TEXT NOT NULL,
  notes TEXT NOT NULL,
  transaction_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (production_order_id, zone_id, transaction_type, reference)
);

-- Single-row plant working-hours calendar. NULL work_start/work_end (or no
-- selected days) means 24/7. Times are wall-clock in time_zone; work_days is a
-- comma-separated list of weekday numbers, Monday = 0.
CREATE TABLE IF NOT EXISTS plant_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  work_start TIME,
  work_end TIME,
  work_days TEXT,
  time_zone TEXT NOT NULL DEFAULT 'UTC'
);
INSERT INTO plant_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Labor standard: indirect adders applied on top of each station's direct
-- labor minutes from the routing plan.
CREATE TABLE IF NOT EXISTS labor_overheads (
  category TEXT PRIMARY KEY,
  description TEXT NOT NULL,
  pct NUMERIC(5, 2) NOT NULL CHECK (pct >= 0)
);
INSERT INTO labor_overheads (category, description, pct) VALUES
  ('material_handling', 'Material handling and staging between stations', 12),
  ('qa_review', 'QA review and documentation of station output', 8),
  ('rework_disposition', 'Rework triage and disposition allowance', 5)
ON CONFLICT (category) DO NOTHING;

-- Operator signoffs recorded from the station page's standard script.
CREATE TABLE IF NOT EXISTS station_signoffs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  order_no TEXT,
  operator TEXT NOT NULL,
  result TEXT NOT NULL CHECK (result IN ('pass', 'fail')),
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===== Standard absorption costing =====

-- Chart of accounts for the plant cost ledger.
CREATE TABLE IF NOT EXISTS gl_accounts (
  account_no TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  account_type TEXT NOT NULL CHECK (account_type IN ('asset', 'liability', 'equity', 'income', 'expense', 'variance')),
  normal_side TEXT NOT NULL CHECK (normal_side IN ('debit', 'credit'))
);
INSERT INTO gl_accounts (account_no, name, account_type, normal_side) VALUES
  ('1310', 'Raw Materials Inventory', 'asset', 'debit'),
  ('1315', 'Subassembly Inventory - Cases', 'asset', 'debit'),
  ('1320', 'Work in Process', 'asset', 'debit'),
  ('1330', 'Finished Goods - Drones', 'asset', 'debit'),
  ('2110', 'Payroll Applied', 'liability', 'credit'),
  ('2120', 'Overhead Applied', 'liability', 'credit'),
  ('3000', 'Opening Balance Equity', 'equity', 'credit'),
  ('5210', 'Material Price Variance', 'variance', 'debit'),
  ('5220', 'Material Usage Variance', 'variance', 'debit'),
  ('5230', 'Labor Rate Variance', 'variance', 'debit'),
  ('5240', 'Labor Efficiency Variance', 'variance', 'debit'),
  ('5250', 'Overhead Absorption Variance', 'variance', 'debit'),
  ('5260', 'Standards Revaluation', 'variance', 'debit')
ON CONFLICT DO NOTHING;

-- Material standards: standard cost drives WIP/FG valuation; the simulated
-- actual price generates purchase price variance at issue.
CREATE TABLE IF NOT EXISTS standard_costs (
  part_number TEXT PRIMARY KEY,
  standard_cost NUMERIC(12, 2) NOT NULL CHECK (standard_cost >= 0),
  actual_cost NUMERIC(12, 2) NOT NULL CHECK (actual_cost >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO standard_costs (part_number, standard_cost, actual_cost) VALUES
  ('DRN-FRM-001', 85.00, 87.50),
  ('DRN-ARM-001', 42.00, 41.20),
  ('DRN-HDW-001', 6.50, 6.50),
  ('DRN-MTR-001', 22.00, 23.10),
  ('DRN-ESC-001', 18.00, 17.60),
  ('DRN-PDB-001', 15.00, 15.75),
  ('DRN-BAT-001', 55.00, 58.00),
  ('DRN-PWR-001', 12.00, 11.70),
  ('DRN-FC-001', 95.00, 92.00),
  ('DRN-RX-001', 28.00, 28.00),
  ('DRN-GPS-001', 32.00, 33.60),
  ('DRN-CAM-001', 48.00, 46.80),
  ('DRN-WIR-001', 9.50, 9.90),
  ('DRN-FW-001', 4.00, 4.00),
  ('DRN-PROP-001', 9.00, 9.45),
  ('DRN-LBL-001', 2.50, 2.50),
  ('DRN-DOC-001', 3.00, 2.85),
  ('DRN-PKG-001', 14.00, 14.60),
  ('CASE-SHL-001', 38.00, 39.90),
  ('CASE-FOAM-001', 16.00, 15.20),
  ('CASE-HNG-001', 9.00, 9.00),
  ('CASE-LTC-001', 6.00, 6.30),
  ('CASE-HDL-001', 5.00, 4.85),
  ('CASE-SEAL-001', 7.50, 7.95),
  ('CASE-HW-001', 4.50, 4.50),
  ('CASE-LBL-001', 3.00, 3.15)
ON CONFLICT (part_number) DO NOTHING;

-- Labor standards by routing role: standard rate absorbs into WIP; the
-- simulated actual rate generates labor rate variance at completion.
CREATE TABLE IF NOT EXISTS labor_rates (
  role TEXT PRIMARY KEY,
  standard_rate NUMERIC(8, 2) NOT NULL CHECK (standard_rate >= 0),
  actual_rate NUMERIC(8, 2) NOT NULL CHECK (actual_rate >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO labor_rates (role, standard_rate, actual_rate) VALUES
  ('Material handler', 26.00, 27.00),
  ('Inventory clerk', 24.00, 24.00),
  ('Mechanical assembler', 34.00, 33.25),
  ('Electrical assembler', 38.00, 39.50),
  ('Test technician', 36.00, 36.00),
  ('Quality technician', 40.00, 41.00),
  ('Packaging operator', 28.00, 27.50),
  ('Forming operator', 32.00, 33.00),
  ('Fabrication operator', 33.00, 32.50)
ON CONFLICT (role) DO NOTHING;

-- Double-entry cost ledger: one entry per costing event (idempotent by
-- event_ref), balanced debit/credit lines against gl_accounts.
CREATE TABLE IF NOT EXISTS cost_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ref TEXT NOT NULL UNIQUE,
  production_order_id INTEGER REFERENCES production_orders(id) ON DELETE CASCADE,
  order_no TEXT,
  event_type TEXT NOT NULL,
  memo TEXT NOT NULL DEFAULT '',
  posted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS cost_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id INTEGER NOT NULL REFERENCES cost_entries(id) ON DELETE CASCADE,
  account_no TEXT NOT NULL REFERENCES gl_accounts(account_no),
  debit NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (credit >= 0)
);
CREATE INDEX IF NOT EXISTS idx_cost_lines_entry ON cost_lines(entry_id);
CREATE INDEX IF NOT EXISTS idx_cost_lines_account ON cost_lines(account_no);
CREATE INDEX IF NOT EXISTS idx_cost_entries_order ON cost_entries(production_order_id);

-- Control: posted journal entries are immutable (no UPDATE; deletes happen
-- only through order cascade or the sanctioned demo reset).
CREATE OR REPLACE FUNCTION forbid_ledger_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Cost ledger entries are immutable';
END;
$$;
DROP TRIGGER IF EXISTS cost_entries_immutable ON cost_entries;
CREATE TRIGGER cost_entries_immutable
  BEFORE UPDATE ON cost_entries
  FOR EACH ROW EXECUTE FUNCTION forbid_ledger_update();
DROP TRIGGER IF EXISTS cost_lines_immutable ON cost_lines;
CREATE TRIGGER cost_lines_immutable
  BEFORE UPDATE ON cost_lines
  FOR EACH ROW EXECUTE FUNCTION forbid_ledger_update();

-- Per-order cost summary and variances, written once at completion.
CREATE TABLE IF NOT EXISTS order_costs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL UNIQUE REFERENCES production_orders(id) ON DELETE CASCADE,
  order_no TEXT NOT NULL,
  sku TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  std_dm NUMERIC(12, 2) NOT NULL,
  std_dl NUMERIC(12, 2) NOT NULL,
  std_oh NUMERIC(12, 2) NOT NULL,
  std_total NUMERIC(12, 2) NOT NULL,
  actual_dm NUMERIC(12, 2) NOT NULL,
  actual_dl NUMERIC(12, 2) NOT NULL,
  actual_oh NUMERIC(12, 2) NOT NULL,
  ppv NUMERIC(12, 2) NOT NULL,
  usage_variance NUMERIC(12, 2) NOT NULL,
  labor_rate_variance NUMERIC(12, 2) NOT NULL,
  labor_efficiency_variance NUMERIC(12, 2) NOT NULL,
  oh_variance NUMERIC(12, 2) NOT NULL,
  total_variance NUMERIC(12, 2) NOT NULL,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Audit trail for changes to cost standards and labor rates.
CREATE TABLE IF NOT EXISTS standards_audit (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor TEXT NOT NULL,
  item_type TEXT NOT NULL,
  item_key TEXT NOT NULL,
  field TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT
);

-- ===== Sales: customers, sales orders, invoicing =====

-- Customers are master data (survive Reset Activity, like standards).
CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  contact TEXT NOT NULL DEFAULT '',
  terms TEXT NOT NULL DEFAULT 'Net 30',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO customers (name, contact, terms) VALUES
  ('Skyline Inspection Services', 'ops@skyline-inspect.example', 'Net 30'),
  ('Northstar Utilities', 'procurement@northstar.example', 'Net 45'),
  ('Gulf Coast Survey Co.', 'buyer@gulfsurvey.example', 'Net 30')
ON CONFLICT DO NOTHING;

-- Suggested selling prices for the finished goods (editable per order line).
CREATE TABLE IF NOT EXISTS price_list (
  sku TEXT PRIMARY KEY,
  list_price NUMERIC(12, 2) NOT NULL CHECK (list_price >= 0)
);
INSERT INTO price_list (sku, list_price) VALUES
  ('DRN-FG-600', 1495.00),
  ('CASE-FG-500', 289.00)
ON CONFLICT (sku) DO NOTHING;

CREATE TABLE IF NOT EXISTS sales_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  so_no TEXT NOT NULL UNIQUE,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  -- Intake lifecycle: draft (unposted, awaiting review) -> open ->
  -- invoiced; accepted-but-short orders wait as backorder and auto-ship
  -- when stock lands; rejected drafts keep their email link for audit.
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('draft', 'open', 'backorder', 'invoiced', 'cancelled', 'rejected')),
  requested_date DATE,
  source_email_id INTEGER,
  accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sales_order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_order_id INTEGER NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0)
);

-- One invoice per sales order: shipping and invoicing happen together.
CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no TEXT NOT NULL UNIQUE,
  sales_order_id INTEGER NOT NULL UNIQUE REFERENCES sales_orders(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  subtotal NUMERIC(12, 2) NOT NULL,
  cogs NUMERIC(12, 2) NOT NULL,
  invoiced_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Email order intake: raw inbound emails plus the AI classification that
-- may draft a sales order from them. Emails are transactions (purge on
-- reset); message_id keeps IMAP polling idempotent.
CREATE TABLE IF NOT EXISTS inbound_emails (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id TEXT UNIQUE,
  from_name TEXT NOT NULL DEFAULT '',
  from_email TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'order_drafted', 'not_order', 'rejected', 'error')),
  classification TEXT,
  sales_order_id INTEGER REFERENCES sales_orders(id) ON DELETE SET NULL,
  processed_at TIMESTAMPTZ
);

-- ===== Purchasing: vendors, sourcing catalog, EOQ policy, vendor POs =====

-- Vendor master and the sourcing catalog are master data (survive Reset
-- Activity); vendor purchase orders are transactions and purge with it.
CREATE TABLE IF NOT EXISTS vendors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  contact TEXT NOT NULL DEFAULT '',
  terms TEXT NOT NULL DEFAULT 'Net 30',
  lead_time_days INTEGER NOT NULL DEFAULT 7 CHECK (lead_time_days >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per vendor offer for a buy part: model, price, MOQ, availability.
CREATE TABLE IF NOT EXISTS vendor_parts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id INTEGER NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
  part_number TEXT NOT NULL,
  vendor_model TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  moq INTEGER NOT NULL DEFAULT 1 CHECK (moq >= 1),
  lead_time_days INTEGER,
  availability TEXT NOT NULL DEFAULT 'In stock',
  preferred BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (vendor_id, part_number)
);
CREATE INDEX IF NOT EXISTS idx_vendor_parts_part ON vendor_parts(part_number);

-- Quantity discounts: the PO line price picks the deepest break the
-- order quantity qualifies for.
CREATE TABLE IF NOT EXISTS vendor_price_breaks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_part_id INTEGER NOT NULL REFERENCES vendor_parts(id) ON DELETE CASCADE,
  min_qty INTEGER NOT NULL CHECK (min_qty > 1),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  UNIQUE (vendor_part_id, min_qty)
);

-- Purchasing policy inputs for EOQ and reorder point (single row).
CREATE TABLE IF NOT EXISTS purchasing_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ordering_cost NUMERIC(10, 2) NOT NULL DEFAULT 25.00 CHECK (ordering_cost > 0),
  carrying_rate_pct NUMERIC(6, 2) NOT NULL DEFAULT 25.00 CHECK (carrying_rate_pct > 0),
  safety_stock_days INTEGER NOT NULL DEFAULT 5 CHECK (safety_stock_days >= 0),
  planned_annual_builds INTEGER NOT NULL DEFAULT 250 CHECK (planned_annual_builds > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO purchasing_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS purchase_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_no TEXT NOT NULL UNIQUE,
  vendor_id INTEGER NOT NULL REFERENCES vendors(id),
  status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued', 'received')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  received_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id INTEGER NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  part_number TEXT NOT NULL,
  vendor_model TEXT NOT NULL DEFAULT '',
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0)
);

-- Receiving posts DR Raw Materials / CR Accounts Payable at PO prices.
INSERT INTO gl_accounts (account_no, name, account_type, normal_side) VALUES
  ('2000', 'Accounts Payable', 'liability', 'credit')
ON CONFLICT DO NOTHING;

-- Sourcing catalog seeded from July 2026 street-price research (real
-- vendors, models, and prices; quantity breaks modeled on market behavior).
INSERT INTO vendors (name, contact, terms, lead_time_days) VALUES
  ('Holybro', 'sales@holybro.com', 'Net 30', 14),
  ('GensTattu', 'support@genstattu.com', 'Net 30', 10),
  ('RadioMaster', 'orders@radiomasterrc.com', 'Net 30', 12),
  ('iFlight', 'sales@iflight.com', 'Net 30', 12),
  ('Pyrodrone', 'support@pyrodrone.com', 'Net 15', 5),
  ('FPVDroneFrame', 'quotes@fpvdroneframe.com', 'Net 30', 21),
  ('SpeedyFPV', 'sales@speedyfpv.com', 'Net 15', 5),
  ('Rotor Riot', 'shop@rotorriot.com', 'Net 15', 5),
  ('SIYI Technology', 'shop@siyi.biz', 'Net 30', 18),
  ('USA Drone Shop', 'sales@usadroneshop.com', 'Net 15', 7),
  ('Drone-FPV-Racer', 'sales@drone-fpv-racer.com', 'Net 30', 15),
  ('Cobra Foam Inserts', 'quotes@cobrafoaminserts.com', 'Net 30', 20),
  ('Brady', 'industrial@bradycorp.com', 'Net 45', 10),
  ('AmeriPack', 'oem@ameripack.com', 'Net 45', 30),
  ('Southco', 'distribution@southco.com', 'Net 45', 15),
  ('Penn Elcom', 'sales@penn-elcom.com', 'Net 30', 10),
  ('Pelican Products', 'parts@pelican.com', 'Net 30', 10),
  ('FastCap', 'orders@fastcap.com', 'Net 15', 7)
ON CONFLICT DO NOTHING;

INSERT INTO vendor_parts
  (vendor_id, part_number, vendor_model, description, unit_price, moq, lead_time_days, availability, preferred)
SELECT v.id, s.part_number, s.vendor_model, s.description, s.unit_price, s.moq, s.lead, s.avail, s.preferred
FROM (VALUES
  ('FPVDroneFrame', 'DRN-FRM-001', 'CF5-COM v3', 'Commercial 5in carbon frame kit: plates + standoffs', 114.00::numeric, 1, NULL::int, 'Made to order', TRUE),
  ('Pyrodrone', 'DRN-FRM-001', 'Apex 5 O3', 'Hobby freestyle 5in frame kit', 29.99, 1, NULL, 'In stock', FALSE),
  ('FPVDroneFrame', 'DRN-ARM-001', 'CF-ARM-4', 'Carbon fiber arm set, 4mm, 4 pcs', 55.68, 1, NULL, 'Made to order', TRUE),
  ('SpeedyFPV', 'DRN-HDW-001', 'M3-KIT-180', '180pc M3 nylon standoff/screw/nut kit + threadlocker', 3.75, 1, NULL, 'In stock', TRUE),
  ('iFlight', 'DRN-MTR-001', 'XING-E Pro 2306 2450KV', 'Brushless motor CW/CCW, sold each', 15.20, 4, NULL, 'In stock', TRUE),
  ('SpeedyFPV', 'DRN-ESC-001', '45A BLHeli_32', 'Single 45A BLHeli_32 ESC, Dshot1200', 13.52, 1, NULL, 'In stock', TRUE),
  ('Pyrodrone', 'DRN-ESC-001', 'EMAX Formula 32 45A', 'Premium 45A BLHeli_32 ESC', 65.66, 1, NULL, 'In stock', FALSE),
  ('USA Drone Shop', 'DRN-PDB-001', 'Matek PDB-XT60', 'PDB w/ BEC 5V/12V, 2oz copper', 5.28, 1, NULL, 'In stock', TRUE),
  ('GensTattu', 'DRN-BAT-001', 'Tattu G-Tech 5200mAh 4S 35C', 'LiPo 14.8V 5200mAh, XT60 plug', 62.99, 1, NULL, 'In stock', TRUE),
  ('Pyrodrone', 'DRN-PWR-001', 'XT60-CAP-1000', 'XT60 pigtail w/ 35V 1000uF cap, 12AWG', 11.99, 1, NULL, 'In stock', TRUE),
  ('Holybro', 'DRN-FC-001', 'Pixhawk 6C (plastic)', 'FC, STM32H743, dual IMU, vibration isolated', 165.99, 1, NULL, 'In stock', TRUE),
  ('SpeedyFPV', 'DRN-FC-001', 'SpeedyBee F405 V4', 'Hobby FC/ESC 55A stack', 69.99, 1, NULL, 'In stock', FALSE),
  ('RadioMaster', 'DRN-RX-001', 'RP1 V2 ELRS 2.4GHz', 'ExpressLRS nano receiver w/ T antenna', 18.99, 1, NULL, 'In stock', TRUE),
  ('Rotor Riot', 'DRN-GPS-001', 'Matek M10Q-5883', 'GNSS + compass, u-blox SAM-M10Q', 39.99, 1, NULL, 'In stock', TRUE),
  ('SIYI Technology', 'DRN-CAM-001', 'A8 mini', '4K 8MP 6x zoom gimbal camera, 95g, inspection payload', 299.00, 1, NULL, 'In stock', TRUE),
  ('Drone-FPV-Racer', 'DRN-WIR-001', 'DFR-WIREKIT', 'Silicone wire kit 18/20/30AWG + stripper', 10.90, 1, NULL, 'In stock', TRUE),
  ('Pyrodrone', 'DRN-PROP-001', 'Gemfan 5043 3-blade', 'Propeller CW/CCW set of 4', 5.99, 1, NULL, 'In stock', TRUE),
  ('Brady', 'DRN-LBL-001', 'B-427 serial set', 'Serial + FAA Remote ID compliance label set', 2.50, 100, NULL, 'Made to order', TRUE),
  ('Cobra Foam Inserts', 'DRN-PKG-001', 'DRN-BOX-150', 'Box + custom foam insert + accessories bag', 14.00, 100, NULL, 'Made to order', TRUE),
  ('AmeriPack', 'CASE-SHL-001', 'RM-2216 shell set', 'Rotomolded shell blanks, top + bottom, trimmed', 38.00, 50, NULL, 'Made to order', TRUE),
  ('FastCap', 'CASE-FOAM-001', 'Kaizen 57mm set', 'Kaizen foam insert block set', 16.00, 1, NULL, 'In stock', TRUE),
  ('Penn Elcom', 'CASE-HNG-001', 'P0644 18in', 'Continuous hinge, 18in cut with pins', 4.39, 1, NULL, 'In stock', TRUE),
  ('Southco', 'CASE-LTC-001', '700-series draw latch', 'Locking over-center draw latch, stainless', 17.03, 1, NULL, 'In stock', TRUE),
  ('Penn Elcom', 'CASE-HDL-001', 'H1011 spring handle', 'Spring-loaded carry handle, rubber grip', 9.99, 1, NULL, 'In stock', TRUE),
  ('Pelican Products', 'CASE-SEAL-001', 'O-ring + purge valve kit', 'Replacement lid o-ring + manual purge valve', 7.95, 1, NULL, 'In stock', TRUE),
  ('Penn Elcom', 'CASE-HW-001', 'CASE-FAST-KIT', 'Rivets, screws, and insert kit', 4.50, 1, NULL, 'In stock', TRUE),
  ('Brady', 'CASE-LBL-001', 'Case badge set', 'Serial badge + compliance label set', 3.00, 100, NULL, 'Made to order', TRUE)
) AS s(vendor_name, part_number, vendor_model, description, unit_price, moq, lead, avail, preferred)
JOIN vendors v ON v.name = s.vendor_name
ON CONFLICT (vendor_id, part_number) DO NOTHING;

INSERT INTO vendor_price_breaks (vendor_part_id, min_qty, unit_price)
SELECT vp.id, s.min_qty, s.unit_price
FROM (VALUES
  ('FPVDroneFrame', 'DRN-FRM-001', 25, 105.00::numeric),
  ('FPVDroneFrame', 'DRN-FRM-001', 100, 96.90),
  ('FPVDroneFrame', 'DRN-ARM-001', 25, 49.95),
  ('SpeedyFPV', 'DRN-HDW-001', 50, 3.25),
  ('iFlight', 'DRN-MTR-001', 40, 13.99),
  ('iFlight', 'DRN-MTR-001', 100, 12.75),
  ('SpeedyFPV', 'DRN-ESC-001', 40, 11.95),
  ('USA Drone Shop', 'DRN-PDB-001', 100, 4.75),
  ('GensTattu', 'DRN-BAT-001', 10, 59.85),
  ('GensTattu', 'DRN-BAT-001', 50, 55.99),
  ('Holybro', 'DRN-FC-001', 10, 157.69),
  ('Holybro', 'DRN-FC-001', 25, 149.39),
  ('RadioMaster', 'DRN-RX-001', 25, 17.09),
  ('Rotor Riot', 'DRN-GPS-001', 25, 36.75),
  ('SIYI Technology', 'DRN-CAM-001', 10, 284.05),
  ('SIYI Technology', 'DRN-CAM-001', 25, 269.10),
  ('Pyrodrone', 'DRN-PROP-001', 50, 4.99),
  ('Cobra Foam Inserts', 'DRN-PKG-001', 250, 11.90),
  ('AmeriPack', 'CASE-SHL-001', 200, 33.25),
  ('FastCap', 'CASE-FOAM-001', 25, 14.40),
  ('Penn Elcom', 'CASE-HNG-001', 100, 3.85),
  ('Southco', 'CASE-LTC-001', 25, 9.75),
  ('Southco', 'CASE-LTC-001', 100, 6.10),
  ('Penn Elcom', 'CASE-HDL-001', 50, 7.49)
) AS s(vendor_name, part_number, min_qty, unit_price)
JOIN vendors v ON v.name = s.vendor_name
JOIN vendor_parts vp ON vp.vendor_id = v.id AND vp.part_number = s.part_number
ON CONFLICT (vendor_part_id, min_qty) DO NOTHING;

-- Order-to-cash accounts for the cost ledger.
INSERT INTO gl_accounts (account_no, name, account_type, normal_side) VALUES
  ('1200', 'Accounts Receivable', 'asset', 'debit'),
  ('4000', 'Sales Revenue', 'income', 'credit'),
  ('5010', 'Cost of Goods Sold', 'expense', 'debit')
ON CONFLICT DO NOTHING;

-- Internal audit: immutable record of each certification run. The package
-- hash fingerprints the exact evidence certified; certifications survive
-- Reset Activity (audit history is permanent).
CREATE TABLE IF NOT EXISTS audit_certifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_hash TEXT NOT NULL,
  as_of TIMESTAMPTZ NOT NULL,
  actor TEXT NOT NULL DEFAULT 'manual',
  mode TEXT NOT NULL CHECK (mode IN ('claude', 'offline')),
  model TEXT,
  opinion TEXT NOT NULL CHECK (opinion IN ('UNQUALIFIED', 'QUALIFIED', 'ADVERSE')),
  basis TEXT NOT NULL,
  findings TEXT NOT NULL DEFAULT '[]',
  assertions_total INTEGER NOT NULL,
  assertions_passed INTEGER NOT NULL,
  certified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS audit_certifications_immutable ON audit_certifications;
CREATE TRIGGER audit_certifications_immutable
  BEFORE UPDATE ON audit_certifications
  FOR EACH ROW EXECUTE FUNCTION forbid_ledger_update();

-- Traceable build: one record per finished unit, written at order completion.
CREATE TABLE IF NOT EXISTS production_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  serial_no TEXT NOT NULL UNIQUE,
  sku TEXT NOT NULL,
  firmware_version TEXT,
  inspection_result TEXT NOT NULL,
  rework_count INTEGER NOT NULL DEFAULT 0,
  final_zone_id TEXT REFERENCES zones(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Data fixup for databases created before the case line: the drone transport case
-- (CASE-FG-500) is both its own BOM parent on the case line and a component line on
-- the drone BOM, so BOM part numbers are unique per parent instead of globally unique,
-- and BOM lines can carry an inventory-pull source zone. Fresh databases already
-- match these definitions, so every statement here is a safe no-op for them.
ALTER TABLE bom_items DROP CONSTRAINT IF EXISTS bom_items_part_number_key;
ALTER TABLE bom_items ADD COLUMN IF NOT EXISTS source_zone_id TEXT REFERENCES zones(id);
ALTER TABLE zones ADD COLUMN IF NOT EXISTS capacity INTEGER;
ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE bom_items ADD COLUMN IF NOT EXISTS serialized BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bom_items ADD COLUMN IF NOT EXISTS substitute_part_number TEXT;
ALTER TABLE process_steps ADD COLUMN IF NOT EXISTS standard_minutes INTEGER;
-- Serialized parts (captured on build records) and approved substitutes.
-- Idempotent; also re-run by seed.sql so fresh databases get the same flags.
UPDATE bom_items SET serialized = TRUE
WHERE part_number IN ('DRN-MTR-001', 'DRN-ESC-001', 'DRN-FC-001', 'DRN-BAT-001', 'CASE-FG-500');
UPDATE bom_items SET substitute_part_number = 'DRN-PROP-002 (alt vendor matched set)'
WHERE part_number = 'DRN-PROP-001';
UPDATE bom_items SET substitute_part_number = 'CASE-LTC-002 (equivalent draw latch)'
WHERE part_number = 'CASE-LTC-001';
UPDATE process_steps SET standard_minutes = expected_minutes WHERE standard_minutes IS NULL;
-- Chart-of-accounts maintenance: allow income/expense account types.
ALTER TABLE gl_accounts DROP CONSTRAINT IF EXISTS gl_accounts_account_type_check;
ALTER TABLE gl_accounts ADD CONSTRAINT gl_accounts_account_type_check
  CHECK (account_type IN ('asset', 'liability', 'equity', 'income', 'expense', 'variance'));
DO $$
BEGIN
  ALTER TABLE bom_items ADD CONSTRAINT bom_items_parent_part_unique UNIQUE (parent_material_id, part_number);
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
END $$;
ALTER TABLE inventory_items DROP CONSTRAINT IF EXISTS inventory_items_area_check;
ALTER TABLE inventory_items ADD CONSTRAINT inventory_items_area_check
  CHECK (area IN ('Parts', 'Production', 'Sub-assembly', 'Finished Goods'));
-- Email order intake: draft/backorder/rejected lifecycle + email link.
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS source_email_id INTEGER;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;
ALTER TABLE sales_orders DROP CONSTRAINT IF EXISTS sales_orders_status_check;
ALTER TABLE sales_orders ADD CONSTRAINT sales_orders_status_check
  CHECK (status IN ('draft', 'open', 'backorder', 'invoiced', 'cancelled', 'rejected'));
-- Subledger account codes: customers C-1001+, vendors V-2001+. Assigned
-- once, permanent, backfilled in id order; new rows continue the sequence.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS account_code TEXT UNIQUE;
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS account_code TEXT UNIQUE;
DO $$
DECLARE
  base INTEGER;
BEGIN
  SELECT COALESCE(MAX(substring(account_code FROM 3)::int), 1000) INTO base
  FROM customers WHERE account_code ~ '^C-[0-9]+$';
  UPDATE customers c SET account_code = 'C-' || r.n
  FROM (
    SELECT id, base + ROW_NUMBER() OVER (ORDER BY id) AS n
    FROM customers WHERE account_code IS NULL
  ) r
  WHERE c.id = r.id;

  SELECT COALESCE(MAX(substring(account_code FROM 3)::int), 2000) INTO base
  FROM vendors WHERE account_code ~ '^V-[0-9]+$';
  UPDATE vendors v SET account_code = 'V-' || r.n
  FROM (
    SELECT id, base + ROW_NUMBER() OVER (ORDER BY id) AS n
    FROM vendors WHERE account_code IS NULL
  ) r
  WHERE v.id = r.id;
END $$;

CREATE INDEX IF NOT EXISTS idx_zones_facility_order ON zones(facility_id, process_order);
CREATE INDEX IF NOT EXISTS idx_process_steps_order ON process_steps(facility_id, step_number);
CREATE INDEX IF NOT EXISTS idx_inventory_zone ON inventory_balances(zone_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_area ON inventory_items(area);
CREATE INDEX IF NOT EXISTS idx_inventory_items_location ON inventory_items(location_zone_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_status ON inventory_items(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_bom_items_parent ON bom_items(parent_material_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_production_orders_order_no_unique ON production_orders(order_no);
CREATE INDEX IF NOT EXISTS idx_production_orders_status ON production_orders(status);
CREATE INDEX IF NOT EXISTS idx_production_order_operations_order ON production_order_operations(production_order_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_workstation_balances_order ON workstation_balances(production_order_id);
CREATE INDEX IF NOT EXISTS idx_production_order_activity_order ON production_order_activity(production_order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_order ON inventory_transactions(production_order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_workstation_ledger_order ON production_workstation_ledger(production_order_id, transaction_at);
CREATE INDEX IF NOT EXISTS idx_workstation_ledger_zone ON production_workstation_ledger(zone_id, transaction_type);

-- ===== Multi-company accounting foundation (migration 012) =====
-- Company 1 = the plant (holds all existing books + the physical floor);
-- companies scope the ACCOUNTING layer only. Runs in the fixup section so
-- every accounting table already exists. See migrations/012_multi_company.sql.
CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  code TEXT UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO companies (id, name, code) VALUES
  (1, 'Drone Plant', 'PLANT'),
  (2, 'Meridian Components LLC', 'MERIDIAN')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('companies', 'id'), GREATEST((SELECT MAX(id) FROM companies), 1));

-- Chart of accounts scoped per company: PK (account_no) -> (company_id, account_no).
ALTER TABLE cost_lines DROP CONSTRAINT IF EXISTS cost_lines_account_no_fkey;
ALTER TABLE gl_accounts ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'gl_accounts' AND constraint_type = 'PRIMARY KEY'
      AND constraint_name = 'gl_accounts_pkey'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.key_column_usage
    WHERE constraint_name = 'gl_accounts_pkey' AND column_name = 'company_id'
  ) THEN
    ALTER TABLE gl_accounts DROP CONSTRAINT gl_accounts_pkey;
    ALTER TABLE gl_accounts ADD CONSTRAINT gl_accounts_pkey PRIMARY KEY (company_id, account_no);
  END IF;
END $$;

ALTER TABLE cost_entries ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE cost_lines ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'cost_lines' AND constraint_name = 'cost_lines_company_account_fkey'
  ) THEN
    ALTER TABLE cost_lines
      ADD CONSTRAINT cost_lines_company_account_fkey
      FOREIGN KEY (company_id, account_no) REFERENCES gl_accounts(company_id, account_no);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_cost_entries_company ON cost_entries(company_id);
CREATE INDEX IF NOT EXISTS idx_cost_lines_company ON cost_lines(company_id);

-- Subledgers and order-to-cash / procure-to-pay scoped per company.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE price_list ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE inbound_emails ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);

ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_name_key;
ALTER TABLE vendors DROP CONSTRAINT IF EXISTS vendors_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS customers_company_name_key ON customers(company_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS vendors_company_name_key ON vendors(company_id, name);
ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_account_code_key;
ALTER TABLE vendors DROP CONSTRAINT IF EXISTS vendors_account_code_key;
CREATE UNIQUE INDEX IF NOT EXISTS customers_company_code_key ON customers(company_id, account_code);
CREATE UNIQUE INDEX IF NOT EXISTS vendors_company_code_key ON vendors(company_id, account_code);
CREATE INDEX IF NOT EXISTS idx_customers_company ON customers(company_id);
CREATE INDEX IF NOT EXISTS idx_vendors_company ON vendors(company_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_company ON sales_orders(company_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_company ON purchase_orders(company_id);

-- Demo company 2's own minimal chart (its own account numbers; empty books).
INSERT INTO gl_accounts (company_id, account_no, name, account_type, normal_side) VALUES
  (2, '1000', 'Cash', 'asset', 'debit'),
  (2, '1200', 'Accounts Receivable', 'asset', 'debit'),
  (2, '1500', 'Inventory', 'asset', 'debit'),
  (2, '2000', 'Accounts Payable', 'liability', 'credit'),
  (2, '3000', 'Owner Equity', 'equity', 'credit'),
  (2, '4000', 'Service Revenue', 'income', 'credit'),
  (2, '5000', 'Operating Expense', 'expense', 'debit')
ON CONFLICT DO NOTHING;

-- Drop earlier signatures so the generalized functions below fully replace
-- them instead of overloading them.
DROP FUNCTION IF EXISTS next_production_order_no();
DROP FUNCTION IF EXISTS create_production_order(TEXT, INTEGER, DATE, DATE);
DROP FUNCTION IF EXISTS create_production_order(TEXT, INTEGER, DATE, DATE, TEXT);

CREATE OR REPLACE FUNCTION next_production_order_no(p_prefix TEXT DEFAULT 'DRN-PO-')
RETURNS TEXT
LANGUAGE sql
AS $$
  SELECT p_prefix || lpad(
    (
      COALESCE(
        MAX(NULLIF(regexp_replace(order_no, '^' || p_prefix, ''), '')::INTEGER),
        1000
      ) + 1
    )::TEXT,
    4,
    '0'
  )
  FROM production_orders
  WHERE order_no LIKE p_prefix || '%'
    AND regexp_replace(order_no, '^' || p_prefix, '') ~ '^[0-9]+$';
$$;

CREATE OR REPLACE FUNCTION create_production_order(
  p_order_no TEXT,
  p_quantity INTEGER,
  p_due_date DATE,
  p_start_date DATE DEFAULT CURRENT_DATE,
  p_finished_sku TEXT DEFAULT 'DRN-FG-600',
  p_auto_replenish BOOLEAN DEFAULT TRUE
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_id INTEGER;
  v_finished_material_id INTEGER;
  v_facility_id INTEGER;
  v_entry_zone_id TEXT;
  v_entry_zone_name TEXT;
  v_pull RECORD;
  v_available NUMERIC(12, 3);
  v_shortfall INTEGER;
  v_pull_is_manufactured BOOLEAN;
  v_replenish_order_no TEXT;
BEGIN
  IF p_quantity <= 0 THEN
    RAISE EXCEPTION 'Production order quantity must be greater than zero';
  END IF;

  SELECT m.id, z.facility_id
  INTO v_finished_material_id, v_facility_id
  FROM materials m
  JOIN zones z ON z.id = m.default_zone_id
  WHERE m.sku = p_finished_sku
    AND m.material_type = 'finished';

  IF v_finished_material_id IS NULL THEN
    RAISE EXCEPTION 'Finished material % is missing', p_finished_sku;
  END IF;

  SELECT ps.source_zone_id, z.name
  INTO v_entry_zone_id, v_entry_zone_name
  FROM process_steps ps
  JOIN zones z ON z.id = ps.source_zone_id
  WHERE ps.facility_id = v_facility_id
  ORDER BY ps.step_number
  LIMIT 1;

  IF v_entry_zone_id IS NULL THEN
    RAISE EXCEPTION 'Facility % has no process steps for %', v_facility_id, p_finished_sku;
  END IF;

  INSERT INTO production_orders (
    order_no, finished_material_id, quantity, status,
    current_zone_id, start_date, due_date
  )
  VALUES (
    p_order_no, v_finished_material_id, p_quantity, 'planned',
    v_entry_zone_id, p_start_date, p_due_date
  )
  RETURNING id INTO v_order_id;

  INSERT INTO production_order_materials (
    production_order_id, bom_item_id, part_number, description,
    required_quantity, unit, source_zone_id, status
  )
  SELECT
    v_order_id,
    bi.id,
    bi.part_number,
    bi.description,
    bi.quantity * p_quantity,
    bi.unit,
    COALESCE(bi.source_zone_id, bi.station_zone_id, v_entry_zone_id),
    CASE WHEN bi.supply_type = 'buy' THEN 'allocated' ELSE 'planned' END
  FROM bom_items bi
  WHERE bi.parent_material_id = v_finished_material_id
    AND bi.part_number <> p_finished_sku
  ORDER BY bi.id;

  -- Inventory-pull lines (bom_items.source_zone_id set) allocate manufactured
  -- sub-assemblies, such as transport cases, from stocked inventory.
  FOR v_pull IN
    SELECT pom.id AS pom_id, pom.part_number, pom.required_quantity, pom.unit,
           bi.source_zone_id
    FROM production_order_materials pom
    JOIN bom_items bi ON bi.id = pom.bom_item_id
    WHERE pom.production_order_id = v_order_id
      AND bi.source_zone_id IS NOT NULL
  LOOP
    SELECT quantity_available
    INTO v_available
    FROM inventory_items
    WHERE location_zone_id = v_pull.source_zone_id
      AND part_number = v_pull.part_number;

    IF v_available IS NULL OR v_available < v_pull.required_quantity THEN
      UPDATE production_order_materials
      SET status = 'short'
      WHERE id = v_pull.pom_id;

      -- Auto-replenishment: a short manufactured pull (such as the transport
      -- case) auto-creates a linked production order for the shortfall so the
      -- supplying line starts building without manual intervention.
      SELECT EXISTS (
        SELECT 1 FROM materials
        WHERE sku = v_pull.part_number AND material_type = 'finished'
      )
      INTO v_pull_is_manufactured;

      IF p_auto_replenish AND v_pull_is_manufactured THEN
        v_shortfall := CEIL(v_pull.required_quantity - COALESCE(v_available, 0))::INTEGER;
        v_replenish_order_no := next_production_order_no(split_part(v_pull.part_number, '-', 1) || '-PO-');

        PERFORM create_production_order(
          v_replenish_order_no, v_shortfall, p_due_date, p_start_date,
          v_pull.part_number, FALSE
        );

        INSERT INTO production_order_activity (
          production_order_id, activity_type, quantity, notes
        )
        VALUES (
          v_order_id, 'adjusted', v_shortfall,
          'Shortage of ' || v_pull.part_number || ': auto-created replenishment order '
            || v_replenish_order_no || ' for ' || v_shortfall || ' each.'
        );
      END IF;
    ELSE
      UPDATE inventory_items
      SET quantity_allocated = quantity_allocated + v_pull.required_quantity,
          updated_at = now()
      WHERE location_zone_id = v_pull.source_zone_id
        AND part_number = v_pull.part_number;

      UPDATE production_order_materials
      SET status = 'allocated'
      WHERE id = v_pull.pom_id;

      INSERT INTO inventory_transactions (
        production_order_id, transaction_type, from_zone_id, part_number,
        quantity, unit, reference
      )
      VALUES (
        v_order_id, 'allocate', v_pull.source_zone_id, v_pull.part_number,
        v_pull.required_quantity, v_pull.unit, p_order_no
      );
    END IF;
  END LOOP;

  INSERT INTO production_order_operations (
    production_order_id, process_step_id, sequence_number, zone_id,
    operation_name, planned_minutes, quantity_in, status
  )
  SELECT
    v_order_id,
    ps.id,
    ps.step_number,
    ps.target_zone_id,
    ps.name,
    ps.expected_minutes,
    CASE WHEN ps.step_number = 1 THEN p_quantity ELSE 0 END,
    CASE WHEN ps.step_number = 1 THEN 'ready' ELSE 'queued' END
  FROM process_steps ps
  WHERE ps.facility_id = v_facility_id
  ORDER BY ps.step_number;

  INSERT INTO workstation_balances (
    production_order_id, zone_id, wip_quantity, completed_quantity, hold_quantity
  )
  SELECT
    v_order_id,
    z.id,
    CASE WHEN z.id = v_entry_zone_id THEN p_quantity ELSE 0 END,
    0,
    0
  FROM zones z
  WHERE z.facility_id = v_facility_id
    AND (
      z.id = v_entry_zone_id
      OR z.id IN (
        SELECT ps.target_zone_id
        FROM process_steps ps
        WHERE ps.facility_id = v_facility_id
      )
    )
  ORDER BY z.process_order;

  INSERT INTO production_order_activity (
    production_order_id, activity_type, to_zone_id, quantity, notes
  )
  VALUES (
    v_order_id, 'created', v_entry_zone_id, p_quantity,
    'Production order created at ' || v_entry_zone_name ||
    ' for testing before material release to the finished goods route.'
  );

  INSERT INTO inventory_transactions (
    production_order_id, transaction_type, to_zone_id, part_number,
    quantity, unit, reference
  )
  VALUES (
    v_order_id, 'create', v_entry_zone_id, p_finished_sku,
    p_quantity, 'each', p_order_no
  );

  INSERT INTO production_workstation_ledger (
    production_order_id, zone_id, transaction_type, quantity_in,
    balance_after, accounting_event, reference, notes
  )
  VALUES (
    v_order_id, v_entry_zone_id, 'in', p_quantity,
    p_quantity, 'WIP_RECEIPT', p_order_no || '-' || v_entry_zone_id || '-in',
    'Initial production order quantity received into ' || v_entry_zone_name || ' WIP.'
  );

  RETURN v_order_id;
END;
$$;

-- Deletes all production activity while preserving the header entities
-- (facilities, zones, materials, process_steps, bom_items, and the
-- inventory_items / inventory_balances rows themselves). Deleting
-- production_orders cascades to order materials, operations, workstation
-- balances, order activity, and the workstation ledger. Inventory quantities
-- are restored to the seed baseline below - keep the VALUES list in sync
-- with seed.sql when seed stock changes.
CREATE OR REPLACE FUNCTION reset_activity()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM inventory_transactions;
  DELETE FROM production_orders;
  DELETE FROM work_orders;
  DELETE FROM station_signoffs;
  -- Cost ledger resets with activity (including the opening-balance entry,
  -- so costing re-initializes from restored stock). Standards and rates
  -- persist as master data.
  DELETE FROM cost_entries;
  -- DEVELOPMENT MODE: purge ALL transaction history, including audit
  -- certifications and the standards change log. Certification permanence
  -- ("audit history survives reset") is intentionally disabled during
  -- development and will be restored before production hardening.
  DELETE FROM audit_certifications;
  DELETE FROM standards_audit;
  -- Sales transactions purge too; customers and the price list persist.
  DELETE FROM inbound_emails;
  DELETE FROM invoices;
  DELETE FROM sales_orders;
  -- Vendor POs purge; vendors, the sourcing catalog, and purchasing
  -- policy settings persist as master data.
  DELETE FROM purchase_orders;

  UPDATE inventory_items AS i
  SET quantity_on_hand = baseline.on_hand,
      quantity_allocated = baseline.allocated,
      updated_at = now()
  FROM (
    VALUES
      ('DRN-FRM-001', 'raw', 12::NUMERIC, 1::NUMERIC),
      ('DRN-ARM-001', 'raw', 12, 1),
      ('DRN-MTR-001', 'raw', 48, 4),
      ('DRN-ESC-001', 'ws2', 40, 4),
      ('DRN-FC-001', 'ws2', 10, 1),
      ('DRN-BAT-001', 'ws2', 8, 1),
      ('DRN-PROP-001', 'ws4', 18, 1),
      ('DRN-PKG-001', 'fg', 9, 1),
      ('DRN-WIP-AIR', 'ws1', 1, 1),
      ('DRN-WIP-ELEC', 'ws2', 0, 0),
      ('DRN-WIP-FW', 'ws3', 0, 0),
      ('DRN-WIP-QA', 'ws5', 0, 0),
      ('DRN-WIP-RWK', 'raw', 0, 0),
      ('DRN-FG-600', 'inventory', 3, 1),
      ('CASE-SHL-001', 'cws1', 14, 1),
      ('CASE-FOAM-001', 'cws2', 10, 1),
      ('CASE-LTC-001', 'cws3', 30, 2),
      ('CASE-LBL-001', 'cws4', 16, 1),
      ('CASE-WIP-FORM', 'cws1', 0, 0),
      ('CASE-FG-500', 'case_inventory', 4, 0)
  ) AS baseline(part_number, location_zone_id, on_hand, allocated)
  WHERE i.part_number = baseline.part_number
    AND i.location_zone_id = baseline.location_zone_id;
END;
$$;
