-- Production support: labor overheads, material-release kit attributes,
-- station signoffs, and traceable build records. For databases created before
-- this feature; fresh databases get everything from schema.sql. Safe to re-run.

ALTER TABLE bom_items ADD COLUMN IF NOT EXISTS serialized BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bom_items ADD COLUMN IF NOT EXISTS substitute_part_number TEXT;
UPDATE bom_items SET serialized = TRUE
WHERE part_number IN ('DRN-MTR-001', 'DRN-ESC-001', 'DRN-FC-001', 'DRN-BAT-001', 'CASE-FG-500');
UPDATE bom_items SET substitute_part_number = 'DRN-PROP-002 (alt vendor matched set)'
WHERE part_number = 'DRN-PROP-001';
UPDATE bom_items SET substitute_part_number = 'CASE-LTC-002 (equivalent draw latch)'
WHERE part_number = 'CASE-LTC-001';

CREATE TABLE IF NOT EXISTS labor_overheads (
  category TEXT PRIMARY KEY,
  description TEXT NOT NULL,
  pct NUMERIC(5, 2) NOT NULL CHECK (pct >= 0)
);
INSERT INTO labor_overheads (category, description, pct) VALUES
  ('material_handling', 'Material handling and staging between stations', 12),
  ('qa_review', 'QA review and documentation of station output', 8),
  ('rework_disposition', 'Rework triage and disposition allowance', 5)
ON CONFLICT (category) DO NOTHING;

CREATE TABLE IF NOT EXISTS station_signoffs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  order_no TEXT,
  operator TEXT NOT NULL,
  result TEXT NOT NULL CHECK (result IN ('pass', 'fail')),
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS production_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  serial_no TEXT NOT NULL UNIQUE,
  sku TEXT NOT NULL,
  firmware_version TEXT,
  inspection_result TEXT NOT NULL,
  rework_count INTEGER NOT NULL DEFAULT 0,
  final_zone_id TEXT REFERENCES zones(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
