-- Standard absorption costing: chart of accounts, material/labor standards,
-- double-entry cost ledger with immutability triggers, per-order cost
-- summaries, and the standards audit trail. For databases created before this
-- feature; fresh databases get everything from schema.sql. Safe to re-run.

ALTER TABLE process_steps ADD COLUMN IF NOT EXISTS standard_minutes INTEGER;
UPDATE process_steps SET standard_minutes = expected_minutes WHERE standard_minutes IS NULL;


-- Chart of accounts for the plant cost ledger.
CREATE TABLE IF NOT EXISTS gl_accounts (
  account_no TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  account_type TEXT NOT NULL CHECK (account_type IN ('asset', 'liability', 'equity', 'variance')),
  normal_side TEXT NOT NULL CHECK (normal_side IN ('debit', 'credit'))
);
INSERT INTO gl_accounts (account_no, name, account_type, normal_side) VALUES
  ('1310', 'Raw Materials Inventory', 'asset', 'debit'),
  ('1315', 'Subassembly Inventory - Cases', 'asset', 'debit'),
  ('1320', 'Work in Process', 'asset', 'debit'),
  ('1330', 'Finished Goods - Drones', 'asset', 'debit'),
  ('2110', 'Payroll Applied', 'liability', 'credit'),
  ('2120', 'Overhead Applied', 'liability', 'credit'),
  ('3000', 'Opening Balance Equity', 'equity', 'credit'),
  ('5210', 'Material Price Variance', 'variance', 'debit'),
  ('5220', 'Material Usage Variance', 'variance', 'debit'),
  ('5230', 'Labor Rate Variance', 'variance', 'debit'),
  ('5240', 'Labor Efficiency Variance', 'variance', 'debit'),
  ('5250', 'Overhead Absorption Variance', 'variance', 'debit')
ON CONFLICT (account_no) DO NOTHING;

-- Material standards: standard cost drives WIP/FG valuation; the simulated
-- actual price generates purchase price variance at issue.
CREATE TABLE IF NOT EXISTS standard_costs (
  part_number TEXT PRIMARY KEY,
  standard_cost NUMERIC(12, 2) NOT NULL CHECK (standard_cost >= 0),
  actual_cost NUMERIC(12, 2) NOT NULL CHECK (actual_cost >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO standard_costs (part_number, standard_cost, actual_cost) VALUES
  ('DRN-FRM-001', 85.00, 87.50),
  ('DRN-ARM-001', 42.00, 41.20),
  ('DRN-HDW-001', 6.50, 6.50),
  ('DRN-MTR-001', 22.00, 23.10),
  ('DRN-ESC-001', 18.00, 17.60),
  ('DRN-PDB-001', 15.00, 15.75),
  ('DRN-BAT-001', 55.00, 58.00),
  ('DRN-PWR-001', 12.00, 11.70),
  ('DRN-FC-001', 95.00, 92.00),
  ('DRN-RX-001', 28.00, 28.00),
  ('DRN-GPS-001', 32.00, 33.60),
  ('DRN-CAM-001', 48.00, 46.80),
  ('DRN-WIR-001', 9.50, 9.90),
  ('DRN-FW-001', 4.00, 4.00),
  ('DRN-PROP-001', 9.00, 9.45),
  ('DRN-LBL-001', 2.50, 2.50),
  ('DRN-DOC-001', 3.00, 2.85),
  ('DRN-PKG-001', 14.00, 14.60),
  ('CASE-SHL-001', 38.00, 39.90),
  ('CASE-FOAM-001', 16.00, 15.20),
  ('CASE-HNG-001', 9.00, 9.00),
  ('CASE-LTC-001', 6.00, 6.30),
  ('CASE-HDL-001', 5.00, 4.85),
  ('CASE-SEAL-001', 7.50, 7.95),
  ('CASE-HW-001', 4.50, 4.50),
  ('CASE-LBL-001', 3.00, 3.15)
ON CONFLICT (part_number) DO NOTHING;

-- Labor standards by routing role: standard rate absorbs into WIP; the
-- simulated actual rate generates labor rate variance at completion.
CREATE TABLE IF NOT EXISTS labor_rates (
  role TEXT PRIMARY KEY,
  standard_rate NUMERIC(8, 2) NOT NULL CHECK (standard_rate >= 0),
  actual_rate NUMERIC(8, 2) NOT NULL CHECK (actual_rate >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO labor_rates (role, standard_rate, actual_rate) VALUES
  ('Material handler', 26.00, 27.00),
  ('Inventory clerk', 24.00, 24.00),
  ('Mechanical assembler', 34.00, 33.25),
  ('Electrical assembler', 38.00, 39.50),
  ('Test technician', 36.00, 36.00),
  ('Quality technician', 40.00, 41.00),
  ('Packaging operator', 28.00, 27.50),
  ('Forming operator', 32.00, 33.00),
  ('Fabrication operator', 33.00, 32.50)
ON CONFLICT (role) DO NOTHING;

-- Double-entry cost ledger: one entry per costing event (idempotent by
-- event_ref), balanced debit/credit lines against gl_accounts.
CREATE TABLE IF NOT EXISTS cost_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ref TEXT NOT NULL UNIQUE,
  production_order_id INTEGER REFERENCES production_orders(id) ON DELETE CASCADE,
  order_no TEXT,
  event_type TEXT NOT NULL,
  memo TEXT NOT NULL DEFAULT '',
  posted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS cost_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id INTEGER NOT NULL REFERENCES cost_entries(id) ON DELETE CASCADE,
  account_no TEXT NOT NULL REFERENCES gl_accounts(account_no),
  debit NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (credit >= 0)
);
CREATE INDEX IF NOT EXISTS idx_cost_lines_entry ON cost_lines(entry_id);
CREATE INDEX IF NOT EXISTS idx_cost_lines_account ON cost_lines(account_no);
CREATE INDEX IF NOT EXISTS idx_cost_entries_order ON cost_entries(production_order_id);

-- Control: posted journal entries are immutable (no UPDATE; deletes happen
-- only through order cascade or the sanctioned demo reset).
CREATE OR REPLACE FUNCTION forbid_ledger_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Cost ledger entries are immutable';
END;
$$;
DROP TRIGGER IF EXISTS cost_entries_immutable ON cost_entries;
CREATE TRIGGER cost_entries_immutable
  BEFORE UPDATE ON cost_entries
  FOR EACH ROW EXECUTE FUNCTION forbid_ledger_update();
DROP TRIGGER IF EXISTS cost_lines_immutable ON cost_lines;
CREATE TRIGGER cost_lines_immutable
  BEFORE UPDATE ON cost_lines
  FOR EACH ROW EXECUTE FUNCTION forbid_ledger_update();

-- Per-order cost summary and variances, written once at completion.
CREATE TABLE IF NOT EXISTS order_costs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL UNIQUE REFERENCES production_orders(id) ON DELETE CASCADE,
  order_no TEXT NOT NULL,
  sku TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  std_dm NUMERIC(12, 2) NOT NULL,
  std_dl NUMERIC(12, 2) NOT NULL,
  std_oh NUMERIC(12, 2) NOT NULL,
  std_total NUMERIC(12, 2) NOT NULL,
  actual_dm NUMERIC(12, 2) NOT NULL,
  actual_dl NUMERIC(12, 2) NOT NULL,
  actual_oh NUMERIC(12, 2) NOT NULL,
  ppv NUMERIC(12, 2) NOT NULL,
  usage_variance NUMERIC(12, 2) NOT NULL,
  labor_rate_variance NUMERIC(12, 2) NOT NULL,
  labor_efficiency_variance NUMERIC(12, 2) NOT NULL,
  oh_variance NUMERIC(12, 2) NOT NULL,
  total_variance NUMERIC(12, 2) NOT NULL,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Audit trail for changes to cost standards and labor rates.
CREATE TABLE IF NOT EXISTS standards_audit (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor TEXT NOT NULL,
  item_type TEXT NOT NULL,
  item_key TEXT NOT NULL,
  field TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT
);

