-- Internal audit certifications: immutable record of each audit run, keyed
-- to a SHA-256 hash of the certified evidence package. For databases created
-- before this feature; fresh databases get it from schema.sql. Safe to re-run.
-- Requires forbid_ledger_update() from migration 005 / schema.sql.

CREATE TABLE IF NOT EXISTS audit_certifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_hash TEXT NOT NULL,
  as_of TIMESTAMPTZ NOT NULL,
  actor TEXT NOT NULL DEFAULT 'manual',
  mode TEXT NOT NULL CHECK (mode IN ('claude', 'offline')),
  model TEXT,
  opinion TEXT NOT NULL CHECK (opinion IN ('UNQUALIFIED', 'QUALIFIED', 'ADVERSE')),
  basis TEXT NOT NULL,
  findings TEXT NOT NULL DEFAULT '[]',
  assertions_total INTEGER NOT NULL,
  assertions_passed INTEGER NOT NULL,
  certified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS audit_certifications_immutable ON audit_certifications;
CREATE TRIGGER audit_certifications_immutable
  BEFORE UPDATE ON audit_certifications
  FOR EACH ROW EXECUTE FUNCTION forbid_ledger_update();
