-- Sales: customers, price list, sales orders, and invoicing, plus the
-- order-to-cash GL accounts. For databases created before this feature;
-- fresh databases get everything from schema.sql. Safe to re-run.

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  contact TEXT NOT NULL DEFAULT '',
  terms TEXT NOT NULL DEFAULT 'Net 30',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO customers (name, contact, terms) VALUES
  ('Skyline Inspection Services', 'ops@skyline-inspect.example', 'Net 30'),
  ('Northstar Utilities', 'procurement@northstar.example', 'Net 45'),
  ('Gulf Coast Survey Co.', 'buyer@gulfsurvey.example', 'Net 30')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS price_list (
  sku TEXT PRIMARY KEY,
  list_price NUMERIC(12, 2) NOT NULL CHECK (list_price >= 0)
);
INSERT INTO price_list (sku, list_price) VALUES
  ('DRN-FG-600', 1495.00),
  ('CASE-FG-500', 289.00)
ON CONFLICT (sku) DO NOTHING;

CREATE TABLE IF NOT EXISTS sales_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  so_no TEXT NOT NULL UNIQUE,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'invoiced', 'cancelled')),
  requested_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sales_order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_order_id INTEGER NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no TEXT NOT NULL UNIQUE,
  sales_order_id INTEGER NOT NULL UNIQUE REFERENCES sales_orders(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  subtotal NUMERIC(12, 2) NOT NULL,
  cogs NUMERIC(12, 2) NOT NULL,
  invoiced_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO gl_accounts (account_no, name, account_type, normal_side) VALUES
  ('1200', 'Accounts Receivable', 'asset', 'debit'),
  ('4000', 'Sales Revenue', 'income', 'credit'),
  ('5010', 'Cost of Goods Sold', 'expense', 'debit')
ON CONFLICT (account_no) DO NOTHING;
