-- 012: Multi-company accounting foundation (Phase 1 of the analytic port).
-- Company 1 = the Drone Plant, holding all existing books and the physical
-- floor. Companies scope the ACCOUNTING layer only (chart of accounts, cost
-- ledger, customers, vendors, sales, purchasing, intake); the physical
-- simulation (facilities, zones, production, inventory, standards) stays
-- company-1-implicit. Idempotent; the same statements live in schema.sql.
--
-- Immutability note: cost_lines/cost_entries carry UPDATE-blocking triggers.
-- ADD COLUMN ... DEFAULT 1 backfills existing rows as a DDL rewrite WITHOUT
-- firing row-level UPDATE triggers, so no per-row UPDATE is needed. The
-- posting engine sets company_id on INSERT (triggers only block UPDATE).

CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  -- Short label for headers/switcher; display only, id stays the key.
  code TEXT UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Company 1 is the plant. Force id = 1 so existing default-1 backfills land here.
INSERT INTO companies (id, name, code)
  VALUES (1, 'Drone Plant', 'PLANT')
  ON CONFLICT (id) DO NOTHING;
-- Company 2 is a demo entity with its own (empty) manual books, to show the
-- switcher and per-company scoping. No physical floor; manual entry lands in
-- a later phase.
INSERT INTO companies (id, name, code)
  VALUES (2, 'Meridian Components LLC', 'MERIDIAN')
  ON CONFLICT (id) DO NOTHING;
-- Keep the identity sequence ahead of the forced ids.
SELECT setval(pg_get_serial_sequence('companies', 'id'), GREATEST((SELECT MAX(id) FROM companies), 1));

-- ===== Chart of accounts: scope per company =====
-- gl_accounts PK moves from (account_no) to (company_id, account_no); the
-- cost_lines FK re-points to the composite key.
ALTER TABLE cost_lines DROP CONSTRAINT IF EXISTS cost_lines_account_no_fkey;

ALTER TABLE gl_accounts ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
DO $$
BEGIN
  -- Swap the single-column PK for the composite one (once).
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'gl_accounts' AND constraint_type = 'PRIMARY KEY'
      AND constraint_name = 'gl_accounts_pkey'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.key_column_usage
    WHERE constraint_name = 'gl_accounts_pkey' AND column_name = 'company_id'
  ) THEN
    ALTER TABLE gl_accounts DROP CONSTRAINT gl_accounts_pkey;
    ALTER TABLE gl_accounts ADD CONSTRAINT gl_accounts_pkey PRIMARY KEY (company_id, account_no);
  END IF;
END $$;

-- ===== Cost ledger: scope entries and lines =====
ALTER TABLE cost_entries ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE cost_lines ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
-- Re-point the line->account FK to the composite key (idempotent).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'cost_lines' AND constraint_name = 'cost_lines_company_account_fkey'
  ) THEN
    ALTER TABLE cost_lines
      ADD CONSTRAINT cost_lines_company_account_fkey
      FOREIGN KEY (company_id, account_no) REFERENCES gl_accounts(company_id, account_no);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_cost_entries_company ON cost_entries(company_id);
CREATE INDEX IF NOT EXISTS idx_cost_lines_company ON cost_lines(company_id);

-- ===== Subledgers and order-to-cash / procure-to-pay: scope per company =====
ALTER TABLE customers ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE price_list ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);
ALTER TABLE inbound_emails ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id);

-- customers/vendors unique-by-name becomes unique per company.
ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_name_key;
ALTER TABLE vendors DROP CONSTRAINT IF EXISTS vendors_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS customers_company_name_key ON customers(company_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS vendors_company_name_key ON vendors(company_id, name);
-- Account codes are unique per company too (C-1001+ can restart per company).
ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_account_code_key;
ALTER TABLE vendors DROP CONSTRAINT IF EXISTS vendors_account_code_key;
CREATE UNIQUE INDEX IF NOT EXISTS customers_company_code_key ON customers(company_id, account_code);
CREATE UNIQUE INDEX IF NOT EXISTS vendors_company_code_key ON vendors(company_id, account_code);

CREATE INDEX IF NOT EXISTS idx_customers_company ON customers(company_id);
CREATE INDEX IF NOT EXISTS idx_vendors_company ON vendors(company_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_company ON sales_orders(company_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_company ON purchase_orders(company_id);

-- Demo company 2's own minimal chart (its own account numbers; empty books).
INSERT INTO gl_accounts (company_id, account_no, name, account_type, normal_side) VALUES
  (2, '1000', 'Cash', 'asset', 'debit'),
  (2, '1200', 'Accounts Receivable', 'asset', 'debit'),
  (2, '1500', 'Inventory', 'asset', 'debit'),
  (2, '2000', 'Accounts Payable', 'liability', 'credit'),
  (2, '3000', 'Owner Equity', 'equity', 'credit'),
  (2, '4000', 'Service Revenue', 'income', 'credit'),
  (2, '5000', 'Operating Expense', 'expense', 'debit')
ON CONFLICT (company_id, account_no) DO NOTHING;
