-- 013: Analytic tags (Phase 2 of the analytic port). A report-only
-- dimensional layer over the cost ledger: tag groups (dimensions), account
-- tags (values), and per-line tag distributions. INTEGRITY RULE: no trial
-- balance or control query joins these tables — the books are byte-identical
-- with or without tag data. Idempotent; mirrored in schema.sql.

CREATE TABLE IF NOT EXISTS tag_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id),
  name TEXT NOT NULL,
  color TEXT,
  UNIQUE (company_id, name)
);

-- An account tag is a value inside a group. `reference` links a tag to the
-- source entity (SKU, customer/vendor account code) for auto-tagging.
CREATE TABLE IF NOT EXISTS account_tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL DEFAULT 1 REFERENCES companies(id),
  tag_group_id INTEGER NOT NULL REFERENCES tag_groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  reference TEXT,
  UNIQUE (tag_group_id, name)
);
CREATE INDEX IF NOT EXISTS idx_account_tags_group ON account_tags(tag_group_id);

-- A cost line's share of a dimension. Report-only; a separate table so
-- writing tags never touches the immutable ledger.
CREATE TABLE IF NOT EXISTS tag_distributions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cost_line_id INTEGER NOT NULL REFERENCES cost_lines(id) ON DELETE CASCADE,
  account_tag_id INTEGER NOT NULL REFERENCES account_tags(id) ON DELETE CASCADE,
  percentage NUMERIC(7, 4) NOT NULL CHECK (percentage > 0 AND percentage <= 100),
  UNIQUE (cost_line_id, account_tag_id)
);
CREATE INDEX IF NOT EXISTS idx_tag_dist_line ON tag_distributions(cost_line_id);
CREATE INDEX IF NOT EXISTS idx_tag_dist_tag ON tag_distributions(account_tag_id);

-- Seed the plant's four dimensions and their static values.
INSERT INTO tag_groups (company_id, name, color) VALUES
  (1, 'Product Line', '#2563eb'),
  (1, 'Cost Center', '#059669'),
  (1, 'Customer', '#d97706'),
  (1, 'Vendor', '#7c3aed')
ON CONFLICT DO NOTHING;

INSERT INTO account_tags (company_id, tag_group_id, name, reference)
SELECT 1, g.id, v.name, v.ref
FROM (VALUES ('Drone', 'DRN-FG-600'), ('Case', 'CASE-FG-500')) AS v(name, ref)
JOIN tag_groups g ON g.company_id = 1 AND g.name = 'Product Line'
ON CONFLICT DO NOTHING;

INSERT INTO account_tags (company_id, tag_group_id, name, reference)
SELECT 1, g.id, v.name, v.name
FROM (VALUES ('Assembly Line'), ('Case Line')) AS v(name)
JOIN tag_groups g ON g.company_id = 1 AND g.name = 'Cost Center'
ON CONFLICT DO NOTHING;

-- Customer / Vendor tags mirror the subledgers (kept in sync at runtime too).
INSERT INTO account_tags (company_id, tag_group_id, name, reference)
SELECT 1, g.id, c.name, c.account_code
FROM customers c
JOIN tag_groups g ON g.company_id = 1 AND g.name = 'Customer'
WHERE c.company_id = 1 AND c.account_code IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO account_tags (company_id, tag_group_id, name, reference)
SELECT 1, g.id, ven.name, ven.account_code
FROM vendors ven
JOIN tag_groups g ON g.company_id = 1 AND g.name = 'Vendor'
WHERE ven.company_id = 1 AND ven.account_code IS NOT NULL
ON CONFLICT DO NOTHING;
