-- 018_ar_module.sql — ERP Phase C: the AR module.
--
-- Carves Accounts Receivable out of the app's public schema into its own `ar`
-- schema (BC-style module boundary): customers + invoices move via SET SCHEMA
-- (FKs, indexes, and sequences follow; sales_orders keeps referencing
-- ar.customers cross-schema automatically), public keeps compatibility views
-- under the old names, and NEW ar.cash_receipts records payment of an invoice —
-- posting DR Cash (1000) / CR Accounts Receivable (1200) to the shared GL.
-- A receipt row IS the paid marker (one receipt pays one invoice in full), so
-- the AR subledger of open invoices keeps tying to the GL's AR balance.
--
-- Run as superuser in ONE transaction. Not re-runnable (guarded).

BEGIN;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'ar') THEN
    RAISE 'ar schema already exists — migration already applied';
  END IF;
END $$;

CREATE SCHEMA ar;

ALTER TABLE public.customers SET SCHEMA ar;
ALTER TABLE public.invoices SET SCHEMA ar;

CREATE VIEW public.customers AS SELECT * FROM ar.customers;
CREATE VIEW public.invoices AS SELECT * FROM ar.invoices;

CREATE TABLE ar.cash_receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_no TEXT NOT NULL UNIQUE,               -- RCT-<n>
  invoice_id INTEGER NOT NULL UNIQUE REFERENCES ar.invoices (id),
  customer_id INTEGER NOT NULL REFERENCES ar.customers (id),
  company_id INTEGER NOT NULL DEFAULT 1,         -- company scope; master = core.companies
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  received_by TEXT NOT NULL DEFAULT '',
  memo TEXT NOT NULL DEFAULT '',
  gl_event_ref TEXT,                             -- ref of the DR 1000 / CR 1200 post
  received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER SCHEMA ar OWNER TO manufacturing;
ALTER TABLE ar.cash_receipts OWNER TO manufacturing;
ALTER VIEW public.customers OWNER TO manufacturing;
ALTER VIEW public.invoices OWNER TO manufacturing;

DO $$ BEGIN
  IF (SELECT count(*) FROM ar.customers) <> (SELECT count(*) FROM public.customers) THEN
    RAISE 'customers view mismatch';
  END IF;
  IF (SELECT count(*) FROM ar.invoices) <> (SELECT count(*) FROM public.invoices) THEN
    RAISE 'invoices view mismatch';
  END IF;
END $$;

COMMIT;
